### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by mavieth** [icanzilb/EventBlankApp#66]
Are there installation instructions? I have tried to build on my Mac to enter the information but have not succeeded.

**Comment by icanzilb** [comment]
nope, no instructions but other ppl have just downloaded it and it worked for them

**Comment by mavieth** [comment]
Which project are we supposed to build first? The mac version?

**Comment by icanzilb** [comment]
there is no mac app to build - the project hasn't been yet officially released
